live_component:
    resource: '@LiveComponentBundle/Resources/config/routing/live_component.xml'

controllers:
    resource: ../src/Controller/
    type: annotation
    prefix:
        en: ''
        fr: '/fr'

kernel:
    resource: ../src/Kernel.php
    type: annotation
